### ISSUE TITLE
Allow admins to create on-chain groups on the Dashboard

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/zk-groups#51]
**Tasks:**

- [x] Integrate the Semaphore subgraph
- [x] Integrate the Metamask wallet
- [x] #62

**Comment by rachelaux** [comment]
Design needs: button to create a group, input for name, select depth of merkel tree, manually add members (copy and paste id commitment)

**Comment by rachelaux** [comment]
i made a separate card that contains the design tasks for this item. So i'm going to remove the design tag on this card so I can better see what i need to work on. Let me know if that's not how I'm supposed to use the design tag

**Comment by cedoor** [comment]
> i made a separate card that contains the design tasks for this item. So i'm going to remove the design tag on this card so I can better see what i need to work on. Let me know if that's not how I'm supposed to use the design tag

Yep right! I added your design tasks as a sub-task of this issue. Does it make sense?
