### ISSUE TITLE
Add Dashboard filters (group type) and sorting (group name)

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/zk-groups#53]

**Comment by rachelaux** [comment]
what kind of group-type filters do you want?

**Comment by cedoor** [comment]
> what kind of group-type filters do you want?

We discussed about the possibility to filter groups by type, but we need to better understand what we mean by "type". We should have two types of groups now:

- Permissioned off-chain groups
- Permissioned on-chain groups

How do they sound?

**Comment by rachelaux** [comment]
if we use the flow that we talked about, Scenario B, users will have two different sign in paths. One to see on-chain groups, one to see off-chain groups. So we will not need the ability to filter those groups.

**Comment by rachelaux** [comment]
The only other group differentiator that comes to mind for me is the tree depth/capacity of the group. 

![Image](https://user-images.githubusercontent.com/81319667/202874374-4514ad8b-567e-48fa-8feb-600982c2649f.png)

**Comment by cedoor** [comment]
> The only other group differentiator that comes to mind for me is the tree depth/capacity of the group.

Makes sense!
